# Generated by Django 6.1 on 2026-08-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
