# Generated by Django 6.1 on 2026-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_category_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_available_from",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_available_till",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
