# Generated by Django 6.1 on 2026-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_menuitem_is_available_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="per_day_selling_units",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
