# Generated by Django 6.1 on 2026-08-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_menuitem_per_day_selling_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="selling_unit_tracking",
            field=models.BooleanField(default=True),
        ),
    ]
