# Generated by Django 6.1 on 2026-08-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_menuitem_selling_unit_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="available_tracking",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="per_day_total_selling_units",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
