# Generated by Django 6.1 on 2026-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_menuitem_available_tracking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="per_day_total_selling_units",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="total_selling_units",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="per_day_selling_units",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
