# Generated by Django 6.1 on 2026-08-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_remove_menuitem_per_day_total_selling_units_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="selling_unit_tracking",
            new_name="disible_by_selling_unit",
        ),
    ]
