# Generated by Django 6.1 on 2026-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_customerreview_runningoffer_menuitem_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_selling_unit_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
