# Generated by Django 6.1 on 2026-09-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menuitem_is_selling_unit_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningoffer',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for an offer with no expiry date.', null=True),
        ),
        migrations.AddField(
            model_name='runningoffer',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave blank to make the offer visible immediately (subject to Active being on).', null=True),
        ),
    ]
