# Generated by Django 6.1 on 2026-09-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_runningoffer_end_date_runningoffer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='If enabled, customers pre-book this item instead of ordering it for immediate fulfillment.', verbose_name='Pre-Order'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preorder_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Hours of notice required before this item can be fulfilled, e.g. 24. Only used when Pre-Order is enabled.', null=True, verbose_name='Pre-Order Hours'),
        ),
    ]
