# Generated by Django 6.1 on 2026-09-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_menuitem_is_preorder_menuitem_preorder_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='available_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
